# Generated by Django 5.1.3 on 2024-12-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('members', models.JSONField(default=[])),
                ('totalmembers', models.IntegerField(default=0)),
                ('payments', models.JSONField(default=[])),
                ('totalpayment', models.IntegerField(default=0)),
                ('paymentpermember', models.IntegerField(default=0)),
                ('dues', models.JSONField(default=[])),
            ],
        ),
    ]
